// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides an AI-generated explanation for why a particular meme coin was chosen for a trade call.
 *
 * - explainWhyThisCoin - A function that generates the explanation.
 * - ExplainWhyThisCoinInput - The input type for the explainWhyThisCoin function.
 * - ExplainWhyThisCoinOutput - The return type for the explainWhyThisCoin function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainWhyThisCoinInputSchema = z.object({
  coinName: z.string().describe('The name of the meme coin.'),
  technicalAnalysis: z.string().describe('Technical analysis data for the meme coin.'),
  marketSentiment: z.string().describe('Market sentiment data for the meme coin.'),
});
export type ExplainWhyThisCoinInput = z.infer<typeof ExplainWhyThisCoinInputSchema>;

const ExplainWhyThisCoinOutputSchema = z.object({
  explanation: z
    .string()
    .describe(
      'Uma explicação abrangente de por que a meme coin foi selecionada, com base na análise técnica e no sentimento de mercado.'
    ),
});
export type ExplainWhyThisCoinOutput = z.infer<typeof ExplainWhyThisCoinOutputSchema>;

export async function explainWhyThisCoin(input: ExplainWhyThisCoinInput): Promise<ExplainWhyThisCoinOutput> {
  return explainWhyThisCoinFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainWhyThisCoinPrompt',
  input: {schema: ExplainWhyThisCoinInputSchema},
  output: {schema: ExplainWhyThisCoinOutputSchema},
  prompt: `Você é um assistente de IA que fornece explicações concisas e informativas sobre por que uma determinada meme coin foi escolhida para um alerta de trade.

  Resuma os seguintes dados de análise técnica e sentimento de mercado para justificar o alerta. Seja claro, direto e inspire confiança no usuário.

  Nome da Moeda: {{{coinName}}}
  Análise Técnica: {{{technicalAnalysis}}}
  Sentimento de Mercado: {{{marketSentiment}}}`,
});

const explainWhyThisCoinFlow = ai.defineFlow(
  {
    name: 'explainWhyThisCoinFlow',
    inputSchema: ExplainWhyThisCoinInputSchema,
    outputSchema: ExplainWhyThisCoinOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
