// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Provides an AI-generated explanation for why a particular meme coin was chosen for a trade call.
 *
 * - explainWhyThisCoin - A function that generates the explanation.
 * - ExplainWhyThisCoinInput - The input type for the explainWhyThisCoin function.
 * - ExplainWhyThisCoinOutput - The return type for the explainWhyThisCoin function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExplainWhyThisCoinInputSchema = z.object({
  coinName: z.string().describe('The name of the meme coin.'),
  technicalAnalysis: z.string().describe('Technical analysis data for the meme coin.'),
  marketSentiment: z.string().describe('Market sentiment data for the meme coin.'),
});
export type ExplainWhyThisCoinInput = z.infer<typeof ExplainWhyThisCoinInputSchema>;

const ExplainWhyThisCoinOutputSchema = z.object({
  explanation: z
    .string()
    .describe(
      'A comprehensive explanation of why the meme coin was selected, based on technical analysis and market sentiment.'
    ),
});
export type ExplainWhyThisCoinOutput = z.infer<typeof ExplainWhyThisCoinOutputSchema>;

export async function explainWhyThisCoin(input: ExplainWhyThisCoinInput): Promise<ExplainWhyThisCoinOutput> {
  return explainWhyThisCoinFlow(input);
}

const prompt = ai.definePrompt({
  name: 'explainWhyThisCoinPrompt',
  input: {schema: ExplainWhyThisCoinInputSchema},
  output: {schema: ExplainWhyThisCoinOutputSchema},
  prompt: `You are an AI assistant that provides concise and informative explanations for why a particular meme coin was chosen for a trade call.

  Summarize the following technical analysis and market sentiment data to justify the call. Be clear, direct, and instill confidence in the user.

  Coin Name: {{{coinName}}}
  Technical Analysis: {{{technicalAnalysis}}}
  Market Sentiment: {{{marketSentiment}}}`,
});

const explainWhyThisCoinFlow = ai.defineFlow(
  {
    name: 'explainWhyThisCoinFlow',
    inputSchema: ExplainWhyThisCoinInputSchema,
    outputSchema: ExplainWhyThisCoinOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
